# Generated by Django 4.2 on 2023-04-20 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0002_alter_order_product_id_alter_order_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="kanban.unittype",
                to_field="name",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="uuid",
            field=models.UUIDField(default="7065d4b8d71d48188852968d739f7481"),
        ),
        migrations.AlterField(
            model_name="products",
            name="uuid",
            field=models.UUIDField(default="39e1cf3917774b578128a6c8ebffa4ee"),
        ),
    ]
