# Generated by Django 4.2 on 2023-04-20 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0003_alter_order_product_id_alter_order_uuid_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="delivery_date",),
        migrations.RemoveField(model_name="order", name="product_id",),
        migrations.RemoveField(model_name="order", name="requested_by",),
        migrations.RemoveField(model_name="order", name="supplier",),
        migrations.RemoveField(model_name="order", name="uuid",),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kanban.unittype",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="uuid",
            field=models.UUIDField(default="94a1803fd1984485a6f89ce604e4cd3e"),
        ),
    ]
