# Generated by Django 4.2 on 2023-04-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0005_alter_order_order_date_alter_products_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="uuid",
            field=models.UUIDField(default="929f613030bf4a469868c1e1a8147f1a"),
        ),
    ]
