# Generated by Django 4.2 on 2023-04-27 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0006_alter_order_order_date_alter_products_uuid"),
    ]

    operations = [
        migrations.RemoveField(model_name="products", name="order_id",),
        migrations.AddField(
            model_name="products",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kanban.order",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="rfid",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inventory",
            name="unit_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kanban.unittype",
            ),
        ),
        migrations.AlterField(
            model_name="partsinventory",
            name="part_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kanban.parttype",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="uuid",
            field=models.UUIDField(default="a00ac0fb7ba04ad7861f705f042a04d9"),
        ),
        migrations.AlterField(
            model_name="unitpartsbom",
            name="part_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kanban.parttype",
            ),
        ),
        migrations.AlterField(
            model_name="unitpartsbom",
            name="unit_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kanban.unittype",
            ),
        ),
    ]
