# Generated by Django 4.2 on 2023-05-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0008_remove_products_uuid_products_product_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="products", name="sent", field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="time_assy1",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="time_assy2",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="time_storage",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="time_warehouse",
            field=models.DateTimeField(null=True),
        ),
    ]
