# Generated by Django 4.2 on 2023-05-04 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0009_products_sent_products_time_assy1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="unit_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kanban.unittype",
            ),
        ),
    ]
